'use client';
import Link from 'next/link';
import { use, useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import { formatMoney, getOrders, saveOrders } from '../../lib/orders';
export default function OrderDetails({ params }) {
  const { id } = use(params); const [order, setOrder] = useState(null); const [employee, setEmployee] = useState('Jane W.');
  useEffect(() => { setOrder(getOrders().find(item => item.id === id) || null); setEmployee(localStorage.getItem('currentEmployee') || 'Jane W.'); }, [id]);
  function approve() { if (!order) return; const approvedAt = new Date().toLocaleTimeString('en-KE', { hour: '2-digit', minute: '2-digit', hour12: false }); const updated = { ...order, paymentStatus: 'PAID', orderStatus: 'COMPLETED', approvedBy: employee, approvedAt }; saveOrders(getOrders().map(item => item.id === order.id ? updated : item)); setOrder(updated); }
  if (!order) return <AppShell><main className="grid min-h-[calc(100vh-64px)] place-items-center"><div className="text-center"><p className="text-lg font-bold">Order not found</p><Link href="/orders" className="mt-3 inline-block text-sm font-bold text-[#3f7139]">Return to orders</Link></div></main></AppShell>;
  const paid = order.paymentStatus === 'PAID';
  return <AppShell><main className="px-5 py-8 sm:px-8 lg:px-10"><div className="mx-auto max-w-2xl"><Link href="/orders" className="text-sm font-bold text-[#4e7143]">← Today&apos;s orders</Link><article className="panel mt-5 overflow-hidden"><header className="border-b border-[#e7ebe4] bg-[#fbfcf8] p-6"><p className="eyebrow">Order record</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">{order.id}</h1><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${paid ? 'bg-[#e8f3e4] text-[#3d7137]' : 'bg-[#fff4db] text-[#97691b]'}`}>{paid ? '✓ PAYMENT PAID' : '◷ AWAITING PAYMENT'}</span></div><p className="mt-2 text-sm text-[#748074]">Recorded today at {order.time} by {order.employee}</p></header><div className="p-6"><div className="grid gap-5 border-b border-[#e7ebe4] pb-6 sm:grid-cols-2"><Info label="Customer" value={order.customer} /><Info label="Payment method" value={order.paymentMethod} /><Info label="Order status" value={order.orderStatus} /><Info label="Recorded by" value={order.employee} /></div><h2 className="mt-6 font-bold">Items ordered</h2><div className="mt-3 divide-y divide-[#edf0eb]">{order.items.map((item, index) => <div key={index} className="flex items-center justify-between py-3"><div><b>{item.name}</b><p className="text-sm text-[#748074]">{formatMoney(item.price)} × {item.quantity}</p></div><b>{formatMoney(item.price * item.quantity)}</b></div>)}</div><div className="mt-4 flex justify-between border-t-2 border-[#203126] pt-4"><span className="text-lg font-bold">Total</span><span className="text-2xl font-bold">{formatMoney(order.total)}</span></div>{!paid ? <div className="mt-7 rounded-2xl bg-[#fff8e8] p-4"><b className="text-[#7f5d19]">Verify the M-Pesa confirmation message</b><p className="mt-1 text-sm leading-5 text-[#806d40]">Only approve after checking the customer&apos;s payment notification.</p><button onClick={approve} className="mt-4 w-full rounded-xl bg-[#2f5b3c] py-3.5 font-bold text-white transition hover:bg-[#234b30]">Confirm payment</button></div> : <div className="mt-7 rounded-2xl bg-[#edf5e9] p-4 text-sm"><b className="text-[#3d7137]">✓ Payment approved</b><p className="mt-1 text-[#597252]">Verified by {order.approvedBy || order.employee} at {order.approvedAt || order.time}.</p></div>}<section className="mt-7 border-t border-[#e7ebe4] pt-5"><h2 className="font-bold">Activity</h2><div className="mt-4 space-y-4 border-l border-[#d9e3d5] pl-4 text-sm"><p><b className="block">{order.time} · Order created</b><span className="text-[#758075]">Recorded by {order.employee}</span></p>{paid && <p><b className="block">{order.approvedAt || order.time} · Payment verified</b><span className="text-[#758075]">Approved by {order.approvedBy || order.employee}</span></p>}</div></section></div></article></div></main></AppShell>;
}
function Info({ label, value }) { return <div><p className="text-xs font-bold uppercase tracking-wider text-[#7d897c]">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
