'use client';

import { useEffect, useMemo, useState } from 'react';
import AppShell from '../components/AppShell';
import { formatMoney, getOrders } from '../lib/orders';

export default function DailySummary() {
  const [orders, setOrders] = useState([]);
  useEffect(() => setOrders(getOrders()), []);
  const stats = useMemo(() => ({ total: orders.reduce((sum, o) => sum + o.total, 0), cash: orders.filter(o => o.paymentMethod === 'Cash').reduce((sum, o) => sum + o.total, 0), mobile: orders.filter(o => o.paymentMethod === 'M-Pesa').reduce((sum, o) => sum + o.total, 0), pending: orders.filter(o => o.paymentStatus === 'PENDING').length, cancelled: orders.filter(o => o.orderStatus === 'CANCELLED').length }), [orders]);
  const staff = useMemo(() => Object.entries(orders.reduce((acc, order) => ({ ...acc, [order.employee]: (acc[order.employee] || 0) + order.total }), {})), [orders]);
  return <AppShell><main className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10"><p className="eyebrow">Daily performance</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Daily summary</h1><p className="mt-2 text-sm text-[#718071]">A clear view of today&apos;s food-order activity.</p><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Stat label="Total orders" value={String(orders.length)} /><Stat label="Total revenue" value={formatMoney(stats.total)} strong /><Stat label="Cash" value={formatMoney(stats.cash)} /><Stat label="Mobile money" value={formatMoney(stats.mobile)} /><Stat label="Pending verification" value={String(stats.pending)} amber /><Stat label="Cancelled" value={String(stats.cancelled)} /></section><section className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="panel p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Payment breakdown</h2><p className="mt-1 text-sm text-[#758075]">Recorded payments by method</p></div><span className="text-xs font-bold text-[#71816d]">Today</span></div><div className="mt-7 space-y-6"><Bar label="Cash" value={stats.cash} total={stats.total} color="bg-[#78a66a]" /><Bar label="Mobile money" value={stats.mobile} total={stats.total} color="bg-[#3f793d]" /></div></div><div className="panel p-5"><h2 className="font-bold">Employee activity</h2><p className="mt-1 text-sm text-[#758075]">Sales recorded per employee</p><div className="mt-5 divide-y divide-[#edf0ea]">{staff.map(([name, value]) => <div key={name} className="flex items-center justify-between py-3"><span className="font-semibold">{name}</span><b>{formatMoney(value)}</b></div>)}{!staff.length && <p className="py-8 text-center text-sm text-[#758075]">No activity recorded yet.</p>}</div></div></section></main></AppShell>;
}
function Stat({ label, value, amber, strong }) { return <div className={`panel p-5 ${amber ? 'border-[#efdca6] bg-[#fffdf7]' : ''}`}><p className="text-sm text-[#748074]">{label}</p><p className={`mt-2 text-2xl font-bold ${strong ? 'text-[#315f30]' : ''}`}>{value}</p></div>; }
function Bar({ label, value, total, color }) { const percent = total ? Math.round((value / total) * 100) : 0; return <div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{label}</span><span className="text-[#667566]">{formatMoney(value)} · {percent}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-[#edf1e9]"><div className={`h-full rounded-full ${color}`} style={{ width: `${percent}%` }} /></div></div>; }
